---
- name: Create an EC2 instance
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: create a new EC2 key pair
      amazon.aws.ec2_key:
        name: vishal_indigo-ws-keypair
      register: aws_ec2_key_pair
      
    - name: Print Key Pair Name
      debug:
        msg: "{{ aws_ec2_key_pair.key.name }}"
        
    - name: create a VPC
      amazon.aws.ec2_vpc_net:
        name: vishal_indigo-ws-vpc
        cidr_block: 10.0.0.0/24
        ipv6_cidr: false
        region: us-east-1
        tenancy: default
      register: vpc
      
    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.0.0/28
        region: us-east-1
        tags:
          Name: vishal_indigo-ws-subnet
      register: subnet
      
    - name: Print Subnet ID
      debug:
        msg: "{{ subnet.subnet.id }}"
        
    - name: Create Security Group
      ec2_group:
        state: present
        name: vishal_indigo-ws-securityGroup
        description: "demo-security-group"
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-1
        rules:
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: "allow all on port 80"
      register: security_group

    - name: Print Security Group ID
      debug:
        msg: "{{ security_group.group_id }}"
        
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "Vishal-Indigo-WS-Instance"
        region: "us-east-1"
        key_name: vj-aaponaws-aug2024
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        instance_type: t2.micro
        security_group: "{{ security_group.group_id }}"
        network:
          assign_public_ip: true
        image_id: ami-0583d8c7a9c35822c
        tags:
          Environment: Testing
      register: ec2

    - name: Print new instance ID
      debug:
        msg: "EC2 instance ID is {{ ec2.instance_ids[0] }}"
