---
- name: Create MySQL Table
  hosts: all
  become: yes
  vars:
    mysql_db_name: BALIC_POC
    mysql_script_name: "mysql_script.sql"
    mysql_validatation_query: "SELECT COUNT(*) FROM balic_table;"
    rows_affected: 2
  vars_files:
    - db_credentials.yml
  pre_tasks:
    - name: Install pip
      yum:
        name: pip
        state: present
    - name: Install mysql client
      pip:
        name: pymysql
        state: present  
  tasks:
    - name: DB - {{ mysql_db_name }} creation Task
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
      register: db_creation_output

    - name: Print DB creation logs
      debug:
        var: db_creation_output

    - name: Copy sql script to target host
      ansible.builtin.copy:
        src: "{{ mysql_script_name }}"
        dest: /home/ansible
      
    - name: Insert Sample Data in to created DB - {{ mysql_db_name }}
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: import
        target: "/home/ansible/{{ mysql_script_name }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
      register: db_import_logs

    - name: Print DB insert logs
      debug:
        var: db_import_logs

    - name: Validate data to ensure proper rows are affected
      mysql_query:
        login_db: "{{ mysql_db_name }}"
        query: "{{ mysql_validatation_query }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
      register: val_result
      failed_when: not val_result.query_result[0] is search("{{ rows_affected }}")
